@"
name: CI/CD with GitOps
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: `${{ secrets.DOCKERHUB_USERNAME }}
          password: `${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          docker build -t `${{ secrets.DOCKERHUB_USERNAME }}/exp1_k8s:`${{ github.sha }} .
          docker push `${{ secrets.DOCKERHUB_USERNAME }}/exp1_k8s:`${{ github.sha }}
      - name: Update Manifest
        run: |
          sed -i "s|image: .*$|image: `${{ secrets.DOCKERHUB_USERNAME }}/exp1_k8s:`${{ github.sha }}|" k8s/deployment.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: update image tag to `${{ github.sha }}"
          git push
"@ | Out-File -FilePath .github\workflows\ci-cd.yaml -Encoding utf8